### ISSUE TITLE
HIGH PRIORITY - New issues found in Web Forms - Relevant in Acknowledge

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#485]
### Actual Behaviour: Relevant in acknowledge is not being evaluated:

![image](https://user-images.githubusercontent.com/29519901/59000433-0fd3d900-87d0-11e9-868f-b1fb576c61bb.png)

![image](https://user-images.githubusercontent.com/29519901/59000470-4d386680-87d0-11e9-9693-306bca48525e.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: There are 2 forms:

![image](https://user-images.githubusercontent.com/29519901/59000512-71944300-87d0-11e9-9c98-d844613d7cac.png)

[EnketoWidgets wo relevant](https://app.kontrolid.com/webForm/s271_11677) just consider evaluate relevance in Acknowledge.

There is an error when I tried to include the same relevance for all questions to check if something else is not working. See  [EnketoWidgets](https://app.kontrolid.com/webForm/s271_11674):

![image](https://user-images.githubusercontent.com/29519901/59000589-c6d05480-87d0-11e9-95ab-a7c58fcd4720.png)

**Comment by nap2000** [comment]
The issue with acknowledge not responding to relevance is fixed.

**Comment by atl2017** [comment]
Tested OK. Could you please check EnketoWidgets in order to do a full test of widgets and verify another potential issues. Thanks

**Comment by nap2000** [comment]
The problem is relevance on the image map.   I'm not sure why this is not working.

**Comment by atl2017** [comment]
You are right. The problem persists only for Image-map. I will raise other
issue with this specific situation.

**Comment by atl2017** [comment]
Hi Neil,

I found out that problem persist not only with image map but Rank question:

![image](https://user-images.githubusercontent.com/29519901/59567182-def56e80-902f-11e9-8da9-fdd7e5ad628b.png)

Please check:

Organisation: KontroliD
Project: Server Updating Test
Form: TestRankQuestion

![image](https://user-images.githubusercontent.com/29519901/59567204-490e1380-9030-11e9-8292-8989993d4228.png)

**Comment by nap2000** [comment]
Fixed and will be released overnight.  Would be better to create new issues rather than reopening old ones as it makes issues easier to track

**Comment by atl2017** [comment]
Thanks. tested OK
